import type { InsightArticle } from "@/lib/insights";
import { softwareCostSlug } from "@/lib/insightRoutes";

// Approved English copy. French and Dutch versions are not yet available.
export const softwareCostArticle: InsightArticle = {
  locale: "en",
  slug: softwareCostSlug,
  translationKey: "custom-business-software-cost-belgium",
  category: "SOFTWARE INVESTMENT",
  title: "How much does custom business software cost in Belgium?",
  introduction: "What determines the budget, which costs should you consider beyond development, and how do you decide whether the investment makes sense for your business?",
  publishedAt: "2026-10-03",
  readingTime: "12 min read",
  metadata: {
    title: "Custom Business Software Cost in Belgium | BrandLabel",
    description: "Understand custom software budgets in Belgium, what changes the price, ongoing costs and how to assess the value of an investment for your business.",
  },
  content: [
    { type: "paragraph", text: "Two companies can ask for a client portal and receive very different quotations." },
    { type: "paragraph", text: "That does not necessarily mean one supplier is expensive and the other affordable." },
    { type: "paragraph", text: "It may mean they are pricing two completely different systems." },
    { type: "paragraph", text: "One portal allows clients to view documents and check a project’s status." },
    { type: "paragraph", text: "The other manages quotations, approvals, payments, access permissions and connections to existing software." },
    { type: "paragraph", text: "The name is the same." },
    { type: "paragraph", text: "The work behind it is not." },
    { type: "paragraph", text: "This is why a meaningful software budget starts with understanding what the system needs to do—not simply what it is called." },
    { type: "heading", level: 2, text: "There is no useful price without a defined scope", id: "there-is-no-useful-price-without-a-defined-scope" },
    { type: "paragraph", text: "“How much does custom software cost?” is a reasonable question." },
    { type: "paragraph", text: "But custom software describes an approach, not a fixed product." },
    { type: "paragraph", text: "It could mean a focused tool that prepares a weekly report." },
    { type: "paragraph", text: "It could mean a client portal connecting customers to an existing project-management system." },
    { type: "paragraph", text: "Or it could mean an operational platform managing planning, projects, documents and internal approvals." },
    { type: "paragraph", text: "Those projects have different requirements, risks and responsibilities." },
    { type: "paragraph", text: "A useful estimate should therefore explain:" },
    { type: "list", items: ["which processes the system will support;","who will use it;","which information it will handle;","which existing tools it must connect to;","what is included in the first version;","and what is deliberately left out."] },
    { type: "paragraph", text: "Without those boundaries, a price can look precise while remaining difficult to interpret." },
    { type: "paragraph", text: "The first objective is not simply to obtain a number." },
    { type: "paragraph", text: "It is to understand what that number includes." },
    { type: "heading", level: 2, text: "What does custom business software cost in Belgium?", id: "what-does-custom-business-software-cost-in-belgium" },
    { type: "paragraph", text: "There is no standard price list for custom software, but publicly available pricing from Belgian software providers gives some useful reference points." },
    { type: "paragraph", text: "For a small or medium-sized business, a focused internal tool addressing one clearly defined process can often fall around €3,000–€10,000." },
    { type: "paragraph", text: "A more complete business application—with several workflows, different user roles, reporting or connections to existing software—often falls around €8,000–€30,000." },
    { type: "paragraph", text: "Projects can go beyond €30,000 when they combine several departments or processes, significant data migration, complex permissions, multiple integrations or broader operational requirements." },
    { type: "paragraph", text: "These ranges overlap deliberately." },
    { type: "paragraph", text: "A client portal, for example, is not automatically a €20,000 project." },
    { type: "paragraph", text: "A relatively focused portal for sharing documents and following requests may sit at the lower end, while one that also handles quotations, approvals, payments and connections to other systems can require a much larger budget." },
    { type: "paragraph", text: "Published Belgian examples also vary considerably between providers. Some position focused internal applications from approximately €3,000–€5,000, while others start more substantial custom projects around €15,000." },
    { type: "paragraph", text: "These figures should therefore be treated as market reference points, not as a price list." },
    { type: "paragraph", text: "The useful question is not only:" },
    { type: "quote", text: "“What type of software are we building?”" },
    { type: "paragraph", text: "It is:" },
    { type: "quote", text: "“What does the software actually need to do?”" },
    { type: "heading", level: 2, text: "What actually affects the development budget?", id: "what-actually-affects-the-development-budget" },
    { type: "paragraph", text: "The number of pages or screens is only part of the picture." },
    { type: "paragraph", text: "A simple-looking screen can contain complicated business rules. A larger interface can support a relatively straightforward process." },
    { type: "paragraph", text: "Several factors deserve particular attention." },
    { type: "heading", level: 3, text: "1. The process behind the interface", id: "1-the-process-behind-the-interface" },
    { type: "paragraph", text: "Consider a quotation approval." },
    { type: "paragraph", text: "In one company, a manager reviews it and clicks “Approve”." },
    { type: "paragraph", text: "In another, approval depends on the amount, department, client type and availability of a second reviewer. Rejected quotations return for revision. Changes must remain traceable." },
    { type: "paragraph", text: "Both systems have an approval button." },
    { type: "paragraph", text: "They do not have the same underlying requirements." },
    { type: "paragraph", text: "The important question is not just what users see." },
    { type: "paragraph", text: "It is what must happen when they act." },
    { type: "heading", level: 3, text: "2. Connections to existing software", id: "2-connections-to-existing-software" },
    { type: "paragraph", text: "Keeping tools that already work can be a sensible decision." },
    { type: "paragraph", text: "But connecting them requires understanding how information will move between them." },
    { type: "paragraph", text: "Which system holds the correct client details?" },
    { type: "paragraph", text: "What happens when a record changes?" },
    { type: "paragraph", text: "What happens if a transfer fails?" },
    { type: "paragraph", text: "A connection is not complete simply because information moves successfully once." },
    { type: "paragraph", text: "It also needs a defined way to handle errors, duplicates and interruptions." },
    { type: "heading", level: 3, text: "3. Existing data", id: "3-existing-data" },
    { type: "paragraph", text: "A new platform may need information currently stored in spreadsheets, shared folders or another application." },
    { type: "paragraph", text: "Importing that information is one task." },
    { type: "paragraph", text: "Preparing it can be another." },
    { type: "paragraph", text: "Duplicate clients, inconsistent dates, missing fields and outdated records all require decisions." },
    { type: "paragraph", text: "Who will clean the information? What should be transferred? What should remain archived?" },
    { type: "paragraph", text: "Those responsibilities should be clear before development begins." },
    { type: "heading", level: 3, text: "4. Access and reliability", id: "4-access-and-reliability" },
    { type: "paragraph", text: "An internal tool used by two colleagues is different from a portal used by employees, external partners and clients." },
    { type: "paragraph", text: "Different users may need different permissions." },
    { type: "paragraph", text: "Clients must not see one another’s information. Former employees should no longer have access. Important records may need a history of changes." },
    { type: "paragraph", text: "Testing, backups and recovery also belong in the discussion." },
    { type: "paragraph", text: "These are not decorative features." },
    { type: "paragraph", text: "They help determine whether the business can depend on the system." },
    { type: "heading", level: 2, text: "A concrete example: the same quotation process, three different projects", id: "a-concrete-example-the-same-quotation-process-three-different-projects" },
    { type: "paragraph", text: "Imagine a service company where quotations are currently prepared in spreadsheets, converted to PDF and sent manually by email." },
    { type: "paragraph", text: "The company asks for a quotation management system." },
    { type: "paragraph", text: "That description alone is not enough to estimate the project." },
    { type: "heading", level: 3, text: "Version 1: remove the repetitive work", id: "version-1-remove-the-repetitive-work" },
    { type: "paragraph", text: "The system stores client details, allows an employee to prepare a quotation from predefined services, calculates the totals, generates a branded PDF and keeps a record of quotations that have been sent." },
    { type: "paragraph", text: "This is one focused workflow." },
    { type: "paragraph", text: "Depending on the exact requirements, a project of this type could reasonably sit in the €3,000–€8,000 range." },
    { type: "heading", level: 3, text: "Version 2: manage the quotation process", id: "version-2-manage-the-quotation-process" },
    { type: "paragraph", text: "Now add different employee permissions, automatic numbering, reusable templates, email delivery, status tracking, reminders and an approval step for quotations above a certain amount." },
    { type: "paragraph", text: "The system is no longer simply generating documents." },
    { type: "paragraph", text: "It is managing the process around them." },
    { type: "paragraph", text: "A project with this level of scope could move into approximately the €8,000–€15,000 range." },
    { type: "heading", level: 3, text: "Version 3: connect quotations to the rest of the operation", id: "version-3-connect-quotations-to-the-rest-of-the-operation" },
    { type: "paragraph", text: "Now suppose an accepted quotation should automatically create a project, notify the appropriate employee, update the CRM, transfer information to the accounting system and give the client access to relevant documents through a portal." },
    { type: "paragraph", text: "The original request is still “a quotation system”." },
    { type: "paragraph", text: "But it has become part of a broader operational platform, and the budget could move beyond €15,000, depending on the integrations, business rules and existing systems involved." },
    { type: "paragraph", text: "The important point is not that every quotation system belongs in one of these price ranges." },
    { type: "paragraph", text: "It is that scope changes the project much more than its name does." },
    { type: "paragraph", text: "Starting with Version 1 or Version 2 may also be perfectly reasonable even if Version 3 is the longer-term objective." },
    { type: "paragraph", text: "The business can solve the immediate problem first and expand the system when there is a demonstrated reason to do so." },
    { type: "heading", level: 2, text: "The development price is not the total cost", id: "the-development-price-is-not-the-total-cost" },
    { type: "paragraph", text: "A quotation for building software does not necessarily include everything required to operate it." },
    { type: "paragraph", text: "Depending on the project, additional costs may include:" },
    { type: "list", items: ["hosting and data storage;","third-party subscriptions;","usage-based services;","maintenance and security updates;","support;","training and documentation;","and future changes."] },
    { type: "paragraph", text: "There is also an internal cost." },
    { type: "paragraph", text: "Someone in the business needs to explain the process, answer questions, test the system and help colleagues adopt it." },
    { type: "paragraph", text: "That time should be planned." },
    { type: "paragraph", text: "A useful comparison therefore looks beyond the launch date." },
    { type: "quote", text: "What will this system cost to build, operate and maintain over the period you expect to use it?" },
    { type: "paragraph", text: "The answer does not need to predict every future expense." },
    { type: "paragraph", text: "It should make the known commitments and remaining uncertainties visible." },
    { type: "heading", level: 2, text: "What makes custom software unnecessarily expensive?", id: "what-makes-custom-software-unnecessarily-expensive" },
    { type: "paragraph", text: "Not every increase in a software budget creates additional value." },
    { type: "paragraph", text: "Some costs come from complexity that the business does not actually need." },
    { type: "heading", level: 3, text: "Trying to solve everything in the first version", id: "trying-to-solve-everything-in-the-first-version" },
    { type: "paragraph", text: "A company may eventually want quotations, planning, project management, invoicing, reporting and a client portal in one system." },
    { type: "paragraph", text: "That does not mean all six need to be built at the same time." },
    { type: "paragraph", text: "Starting with the workflow creating the greatest operational problem can reduce the initial investment and provide useful information before the next part is developed." },
    { type: "heading", level: 3, text: "Rebuilding tools that already work", id: "rebuilding-tools-that-already-work" },
    { type: "paragraph", text: "Custom does not have to mean replacing everything." },
    { type: "paragraph", text: "If the company’s accounting software, CRM or payment system already performs its role well, connecting to it may make more sense than recreating the same functionality." },
    { type: "heading", level: 3, text: "Automating an unnecessarily complicated process", id: "automating-an-unnecessarily-complicated-process" },
    { type: "paragraph", text: "Software can make a process faster." },
    { type: "paragraph", text: "It can also make a bad process faster." },
    { type: "paragraph", text: "If information passes through four people when only two are actually required, reproducing those four steps in software preserves the inefficiency instead of removing it." },
    { type: "paragraph", text: "Sometimes part of the work should therefore happen before development: deciding which steps are genuinely necessary." },
    { type: "heading", level: 3, text: "Designing for hypothetical future requirements", id: "designing-for-hypothetical-future-requirements" },
    { type: "paragraph", text: "It is reasonable to consider growth." },
    { type: "paragraph", text: "It is less useful to build features today because the company might need them several years from now." },
    { type: "paragraph", text: "Future possibilities should influence important architectural decisions without automatically becoming features in the first version." },
    { type: "heading", level: 3, text: "Changing fundamental requirements during development", id: "changing-fundamental-requirements-during-development" },
    { type: "paragraph", text: "Some changes are normal once people begin interacting with a system." },
    { type: "paragraph", text: "Repeatedly changing the underlying workflow is different." },
    { type: "paragraph", text: "If important operational decisions remain unresolved when development starts, parts of the system may need to be redesigned or rebuilt later." },
    { type: "paragraph", text: "A good discovery process is therefore not additional bureaucracy before development." },
    { type: "paragraph", text: "It is one way of avoiding unnecessary development." },
    { type: "heading", level: 2, text: "A lower quotation is not automatically better value", id: "a-lower-quotation-is-not-automatically-better-value" },
    { type: "paragraph", text: "Imagine receiving two proposals." },
    { type: "paragraph", text: "One includes data migration, testing, deployment, documentation and a defined support period." },
    { type: "paragraph", text: "The other includes development, with those items priced separately." },
    { type: "paragraph", text: "The second proposal may still be the right choice." },
    { type: "paragraph", text: "But comparing only the final figures would be misleading." },
    { type: "paragraph", text: "Before comparing prices, compare responsibilities." },
    { type: "paragraph", text: "What will be delivered?" },
    { type: "paragraph", text: "Who will prepare the data?" },
    { type: "paragraph", text: "How will acceptance be agreed?" },
    { type: "paragraph", text: "What happens if a problem appears after launch?" },
    { type: "paragraph", text: "Also clarify access and continuity." },
    { type: "paragraph", text: "Who controls the hosting accounts?" },
    { type: "paragraph", text: "Can your data be exported?" },
    { type: "paragraph", text: "What source-code access or ownership is included?" },
    { type: "paragraph", text: "Could another provider maintain the system later?" },
    { type: "paragraph", text: "These questions are easier to resolve before the business depends on the software." },
    { type: "heading", level: 2, text: "How do you decide whether the investment is worthwhile?", id: "how-do-you-decide-whether-the-investment-is-worthwhile" },
    { type: "paragraph", text: "Start with the process being improved." },
    { type: "paragraph", text: "Consider a hypothetical business spending ten hours each week consolidating project information." },
    { type: "paragraph", text: "At an assumed internal cost of €35 per hour, over 46 working weeks, that represents:" },
    { type: "quote", text: "10 hours × €35 × 46 weeks = €16,100 per year" },
    { type: "paragraph", text: "That is not automatically an amount software can save." },
    { type: "paragraph", text: "Some checks will remain necessary. People will still handle exceptions. The new system will have its own operating costs." },
    { type: "paragraph", text: "Suppose the business estimates that a better process could realistically recover half of that time." },
    { type: "paragraph", text: "The potential capacity released would represent:" },
    { type: "quote", text: "5 hours × €35 × 46 weeks = €8,050 per year" },
    { type: "paragraph", text: "These figures are illustrative, not a pricing benchmark or a promised result." },
    { type: "paragraph", text: "The distinction matters." },
    { type: "paragraph", text: "Recovered time does not automatically become cash savings." },
    { type: "paragraph", text: "It may allow employees to serve more clients, follow up sooner, reduce overtime or handle additional work without immediately increasing administrative capacity." },
    { type: "paragraph", text: "A simple starting calculation is:" },
    { type: "quote", text: "Annual process cost = hours spent each week × internal hourly cost × working weeks" },
    { type: "paragraph", text: "Then estimate conservatively how much of that work could realistically be removed or redirected." },
    { type: "paragraph", text: "Time is also not the only possible return." },
    { type: "paragraph", text: "A better operational process may create value through:" },
    { type: "list", items: ["time recovered — employees can spend more time on higher-value work;","errors avoided — less correction, duplication and rework;","faster operations — quotations, approvals, onboarding or projects move sooner;","additional capacity — the business can handle more activity without immediately increasing administrative resources."] },
    { type: "paragraph", text: "A credible investment case connects the proposed improvement to a practical outcome." },
    { type: "heading", level: 2, text: "Starting smaller can make the decision clearer", id: "starting-smaller-can-make-the-decision-clearer" },
    { type: "paragraph", text: "A company may eventually benefit from a broader operational platform." },
    { type: "paragraph", text: "That does not mean every feature needs to be included at launch." },
    { type: "paragraph", text: "The first version could address one complete workflow:" },
    { type: "paragraph", text: "a request arrives, the right person reviews it, the status is updated and the necessary information reaches the next step." },
    { type: "paragraph", text: "That may be more useful than launching several partially connected modules." },
    { type: "paragraph", text: "A focused first version also creates an opportunity to check assumptions." },
    { type: "paragraph", text: "Do people use it?" },
    { type: "paragraph", text: "Does it remove the expected manual work?" },
    { type: "paragraph", text: "Which exceptions occur in practice?" },
    { type: "paragraph", text: "What should be improved before expanding further?" },
    { type: "paragraph", text: "However, “smaller” should mean a narrower scope." },
    { type: "paragraph", text: "It should not mean removing essential access controls, testing or backups." },
    { type: "heading", level: 2, text: "When spending less means building nothing", id: "when-spending-less-means-building-nothing" },
    { type: "paragraph", text: "Sometimes the most sensible result of an initial review is that custom development is unnecessary." },
    { type: "paragraph", text: "An existing application may already support the requirement." },
    { type: "paragraph", text: "A configuration change may remove the problem." },
    { type: "paragraph", text: "An integration may connect two tools without creating a new platform." },
    { type: "paragraph", text: "A focused automation may eliminate the repetitive work at a fraction of the cost of a larger system." },
    { type: "paragraph", text: "Or the process itself may need simplification before any technology is introduced." },
    { type: "paragraph", text: "Custom software should not be the predetermined answer." },
    { type: "paragraph", text: "It should be one possible response to a clearly understood need." },
    { type: "linkedParagraph", before: "If you are still determining whether your company needs custom development at all, read our guide on ", href: "/insights/custom-business-software-belgium", label: "when a custom business platform is actually necessary for a Belgian SME", after: "." },
    { type: "heading", level: 2, text: "What should you prepare before asking for a quotation?", id: "what-should-you-prepare-before-asking-for-a-quotation" },
    { type: "paragraph", text: "You do not need a technical specification to begin." },
    { type: "paragraph", text: "A clear description of the operation is more useful than a long list of imagined features." },
    { type: "paragraph", text: "Prepare answers to these questions:" },
    { type: "list", ordered: true, items: ["Which process needs to improve?","Who uses it, and how frequently?","Where does work slow down or get repeated?","Which tools and information are involved?","Which exceptions must the system handle?","What must the first version achieve?","What can wait?","How will you judge whether the change was worthwhile?"] },
    { type: "paragraph", text: "This gives the discussion a practical starting point." },
    { type: "paragraph", text: "It also helps distinguish essential requirements from additions that increase the budget without improving the result." },
    { type: "heading", level: 2, text: "The right budget follows the problem", id: "the-right-budget-follows-the-problem" },
    { type: "paragraph", text: "For a Belgian SME considering custom software, the objective should not be to buy the largest platform the budget allows." },
    { type: "paragraph", text: "Nor should it be to find the lowest development price in isolation." },
    { type: "paragraph", text: "The objective is to choose an appropriate solution, understand its ongoing cost and identify the improvement it should create." },
    { type: "paragraph", text: "So when asking:" },
    { type: "quote", text: "“How much will this software cost?”" },
    { type: "paragraph", text: "ask another question alongside it:" },
    { type: "quote", text: "“What will change in the business when it works?”" },
    { type: "paragraph", text: "A useful proposal should help you answer both." },
    { type: "heading", level: 2, text: "Before asking for a software quotation, understand what is costing you today", id: "before-asking-for-a-software-quotation-understand-what-is-costing-you-today" },
    { type: "paragraph", text: "If you’re considering custom software, automation or an integration, start by identifying where time is currently being lost." },
    { type: "paragraph", text: "The BrandLabel Operational Diagnostic helps you estimate the cost of repetitive work and identify which processes may be worth improving." },
    { type: "paragraph", text: "You may discover that you need a custom platform." },
    { type: "paragraph", text: "You may discover that a smaller automation or integration is enough." },
    { type: "paragraph", text: "Or you may discover that changing the process itself should come first." },
    { type: "link", href: "/diagnostic", label: "Start the Operational Diagnostic →" },
  ],
};
