"use client";

import { Container } from "@/components/Container";
import { useLanguage, type Language } from "@/lib/i18n";

const policyText: Record<Language, string[]> = {
  en: [
    "BrandLabel Agency (“we,” “our,” or “us”) is committed to protecting your privacy. This Privacy Policy explains how personal information is collected, used, stored, protected, transferred, and disclosed when you visit brandlabelagency.com, contact us directly, request a report, consultation or quote, or use any related BrandLabel Agency service. BrandLabel Agency, VAT BE1040366570, is the data controller. Privacy enquiries may be sent to contact@brandlabelagency.com.",
    "For this Privacy Policy, “Company,” “we,” “us,” and “our” refer to BrandLabel Agency; “Website” refers to brandlabelagency.com; “Service” refers to the website and any service provided by BrandLabel Agency; “You” refers to the person, company, or organisation using the website or contacting us; “Personal Data” means information that identifies or can reasonably identify a natural person; “Device” means any internet-connected phone, tablet, computer, or similar device; “Cookie” means a small piece of data stored by your browser to remember preferences, support functionality, or provide analytics; and “Third-Party Service” means a provider or partner used to host, operate, analyse, secure, communicate, process payments where applicable, or deliver our services.",
    "We may collect information you provide directly, including your name, username where applicable, company name, email address, phone number where provided, message content, service request details, audit or quote information, order or transaction information where applicable, newsletter or communication preferences where applicable, and any other information you choose to send through a form, email, survey, promotion, order process, account process, or direct communication. We may also collect technical and usage information when you visit the website, including IP address, browser type, device type, operating system, pages visited, dates and times of access, referring pages, approximate location, connection information, language preference, cookie consent choice, and server or security logs.",
    "We collect information when you visit the website, complete a form, contact us directly, request information, request a quote, subscribe to communications where available, respond to a survey or promotion where available, place an order where available, register for an account where available, or otherwise interact with BrandLabel Agency. We may also receive information from Third-Party Services used for hosting, analytics, email delivery, security, fraud prevention, customer communication, database storage, payment processing where applicable, customer service, and publicly available sources such as business websites or social media pages.",
    "We use the information we collect to respond to enquiries, provide audits or quotes, communicate with you, improve the website, personalise your experience, improve customer service, process transactions where applicable, administer forms, surveys or promotions where applicable, send service-related emails, send requested or authorised communications, maintain security, prevent abuse, debug technical issues, analyse website performance, and improve our services. We do not send unsolicited commercial emails. Where marketing emails are used, you may unsubscribe or opt out using the instructions included in those communications.",
    "The legal basis for processing depends on the context. We process contact and enquiry information to respond to your request and take steps before entering into a possible service agreement. We process operational and security information for our legitimate interest in running a secure and reliable website. We process analytics only when you consent to analytics cookies. We may process some information where necessary to comply with legal, accounting, tax, regulatory, or security obligations, or to establish, exercise, or defend legal claims.",
    "We may share personal and non-personal information with trusted Third-Party Services that help us operate the website and deliver services, including hosting providers, email delivery providers, analytics providers, database or storage providers, customer service tools, payment processors where applicable, security providers, professional advisers, and business partners where necessary for the Service. We may also disclose information where required by law, legal process, court order, regulatory request, or where we reasonably believe disclosure is necessary to protect our rights or interests, protect the public or any person, prevent or stop unlawful, unethical, or legally actionable activity, investigate abuse, or comply with applicable laws and regulations.",
    "This website uses cookies and similar technologies to identify areas of the website you have visited, remember preferences, support functionality, improve performance, and provide analytics. Essential preferences may include cookie consent and language preference. Optional analytics cookies, including Google Analytics 4 where configured, are used only after consent to understand how visitors use the website. You may accept or decline non-essential analytics. You can clear your choice through the Cookie settings link in the footer, and you can also block or delete cookies through your browser settings. Blocking or deleting cookies may affect saved preferences or certain website functionality. We do not intentionally place personally identifiable information in cookies.",
    "We may share limited log file data, including IP addresses, with analytics or infrastructure providers for measurement, security, debugging, auditing, research, and reporting. Analytics information may be used to estimate general location, device type, browser type, connection information, pages viewed, and interaction patterns. Analytics data is used to improve the website and services, not to sell personal data.",
    "Anonymous diagnostic answers are not stored. Personal information submitted in connection with a report, consultation, quote or other enquiry that does not lead to a collaboration is retained for no longer than 12 months after the most recent substantive contact. Personal information relating to an active client relationship is retained for the duration of the collaboration and deleted no later than two years after the collaboration ends, unless a longer period is required to comply with a legal, accounting, tax, regulatory or contractual obligation, or to establish, exercise or defend legal claims. Invoices, contracts and other records subject to a mandatory retention period are retained for the period required by applicable law. Analytics information is retained in accordance with the retention settings configured for the relevant analytics provider. When information is no longer required, we will delete or anonymise it where reasonably possible. Backup copies may remain for a limited period where technically necessary to protect against accidental loss.",
    "We use reasonable physical, technical, and organisational measures to protect personal information against unauthorised access, loss, misuse, disclosure, alteration, or destruction. These measures may include secure hosting, access controls, encrypted transmission where available, and internal procedures. However, no website, email transmission, hosting provider, payment provider, encryption system, or security system can be guaranteed to be completely secure, and we cannot guarantee absolute security of information transmitted to or through the Service.",
    "Information collected through the website, direct communication, or Third-Party Services may be processed in Belgium, the European Economic Area, or other countries where our personnel or service providers operate. Where personal data is transferred outside the European Economic Area, the relevant provider is expected to rely on appropriate safeguards such as adequacy decisions, standard contractual clauses, or other lawful transfer mechanisms.",
    "Depending on your relationship with BrandLabel Agency and the laws that apply, you may have rights to access, correct, update, restrict, delete, object to processing of, or request portability of your personal data. You may also withdraw consent where processing is based on consent and change communication preferences where applicable. To protect privacy and security, we may take reasonable steps to verify your identity before responding to a request. Updates, corrections, changes, or deletions may not affect information already lawfully processed, information retained for legal or security reasons, information contained in backups that are difficult or impossible to locate immediately, or information already provided to third parties in accordance with this Privacy Policy before the request was processed.",
    "If you are an end user of one of our customers and wish to update, delete, or receive information held about you in a customer-controlled system, you may need to contact the organisation of which you are a customer. Where BrandLabel Agency acts only as a processor or service provider for a customer, we may direct your request to that customer.",
    "We reserve the right to transfer information to a third party in the event of a sale, merger, acquisition, restructuring, bankruptcy, transfer of assets, discontinuation of business, or similar business transaction involving BrandLabel Agency or any corporate affiliate, provided that the receiving party agrees to handle the information in accordance with this Privacy Policy or an equivalent privacy standard. We may also disclose information, including personal information, to corporate affiliates where applicable. A corporate affiliate means an entity that directly or indirectly controls, is controlled by, or is under common control with BrandLabel Agency.",
    "Our Service may contain links to third-party websites or services that are not operated or controlled by BrandLabel Agency. We are not responsible for the content, accuracy, privacy practices, policies, or security of third-party websites or services. When you leave our website, your browsing and interaction are governed by the third party’s own terms and privacy policy. Third parties may use their own cookies or similar technologies.",
    "BrandLabel Agency does not knowingly collect personally identifiable information from children under the age of 13. If you are a parent or guardian and believe a child has provided Personal Data to us, please contact us. If we become aware that we have collected Personal Data from a child under 13 without appropriate consent, we will take steps to remove that information.",
    "The General Data Protection Regulation (GDPR) gives individuals in the European Economic Area rights over their Personal Data and requires personal data to be processed fairly, lawfully, transparently, for specific purposes, and no longer than necessary. BrandLabel Agency treats GDPR principles as a baseline standard. Personal data should be collected for clear purposes, used in ways people can reasonably expect, protected appropriately, and made available for access, correction, deletion, restriction, objection, or portability where required by applicable law.",
    "This Privacy Policy is governed by the laws of Belgium, without regard to conflict of law rules, subject to any mandatory rights you may have under applicable local, national, European, or international law. Your use of the website may also be subject to other applicable local, national, or international laws.",
    "By using the website, contacting us directly, or continuing to use the Service after this Privacy Policy is updated, you acknowledge that you have read this Privacy Policy. If you do not agree with this Privacy Policy, you should not use the website or submit personal information through the Service. We may update this Privacy Policy when our Service, providers, legal obligations, or business structure change, and the latest version will be posted on this page with an updated date.",
    "If you have questions about this Privacy Policy or wish to make a privacy request, contact us at contact@brandlabelagency.com or use the contact form and include “privacy request” in your message.",
  ],
  fr: [
    "BrandLabel Agency (« nous », « notre » ou « nos ») s’engage à protéger votre vie privée. Cette Politique de confidentialité explique comment les informations personnelles sont collectées, utilisées, stockées, protégées, transférées et communiquées lorsque vous visitez brandlabelagency.com, nous contactez directement, demandez un rapport, une consultation ou un devis, ou utilisez tout service associé à BrandLabel Agency. BrandLabel Agency, TVA BE1040366570, est le responsable du traitement. Toute question relative à la vie privée peut être envoyée à contact@brandlabelagency.com.",
    "Dans cette Politique de confidentialité, « Société », « nous », « notre » et « nos » désignent BrandLabel Agency ; « Site web » désigne brandlabelagency.com ; « Service » désigne le site web et tout service fourni par BrandLabel Agency ; « Vous » désigne la personne, l’entreprise ou l’organisation qui utilise le site web ou nous contacte ; « Données personnelles » désigne toute information permettant d’identifier directement ou raisonnablement une personne physique ; « Appareil » désigne tout téléphone, tablette, ordinateur ou appareil similaire connecté à Internet ; « Cookie » désigne un petit fichier de données stocké par votre navigateur pour mémoriser des préférences, soutenir des fonctionnalités ou fournir des statistiques ; et « Service tiers » désigne un prestataire ou partenaire utilisé pour héberger, exploiter, analyser, sécuriser, communiquer, traiter des paiements lorsque applicable ou fournir nos services.",
    "Nous pouvons collecter les informations que vous fournissez directement, notamment votre nom, nom d’utilisateur lorsque applicable, nom d’entreprise, adresse e-mail, numéro de téléphone lorsque fourni, contenu du message, détails de la demande de service, informations relatives à un audit ou devis, informations de commande ou transaction lorsque applicable, préférences de newsletter ou communication lorsque applicable, ainsi que toute autre information que vous choisissez d’envoyer via un formulaire, e-mail, enquête, promotion, processus de commande, processus de compte ou communication directe. Nous pouvons également collecter des informations techniques et d’utilisation lorsque vous visitez le site web, notamment l’adresse IP, le type de navigateur, le type d’appareil, le système d’exploitation, les pages visitées, les dates et heures d’accès, les pages de provenance, la localisation approximative, les informations de connexion, la préférence de langue, le choix relatif aux cookies, ainsi que les journaux serveur ou de sécurité.",
    "Nous collectons des informations lorsque vous visitez le site web, remplissez un formulaire, nous contactez directement, demandez des informations, demandez un devis, vous abonnez à des communications lorsque cela est disponible, répondez à une enquête ou promotion lorsque cela est disponible, passez une commande lorsque cela est disponible, créez un compte lorsque cela est disponible, ou interagissez autrement avec BrandLabel Agency. Nous pouvons également recevoir des informations de Services tiers utilisés pour l’hébergement, les statistiques, l’envoi d’e-mails, la sécurité, la prévention de la fraude, la communication client, le stockage de bases de données, le traitement des paiements lorsque applicable, le service client et les sources publiques telles que des sites d’entreprises ou pages de réseaux sociaux.",
    "Nous utilisons les informations collectées pour répondre aux demandes, fournir des audits ou devis, communiquer avec vous, améliorer le site web, personnaliser votre expérience, améliorer le service client, traiter des transactions lorsque applicable, administrer des formulaires, enquêtes ou promotions lorsque applicable, envoyer des e-mails liés au service, envoyer des communications demandées ou autorisées, maintenir la sécurité, prévenir les abus, résoudre des problèmes techniques, analyser les performances du site web et améliorer nos services. Nous n’envoyons pas d’e-mails commerciaux non sollicités. Lorsque des e-mails marketing sont utilisés, vous pouvez vous désabonner ou vous opposer en suivant les instructions incluses dans ces communications.",
    "La base juridique du traitement dépend du contexte. Nous traitons les informations de contact et de demande afin de répondre à votre demande et de prendre des mesures avant une éventuelle convention de service. Nous traitons les informations opérationnelles et de sécurité sur la base de notre intérêt légitime à exploiter un site web sûr et fiable. Nous traitons les statistiques uniquement lorsque vous consentez aux cookies d’analyse. Nous pouvons traiter certaines informations lorsque cela est nécessaire pour respecter des obligations légales, comptables, fiscales, réglementaires ou de sécurité, ou pour établir, exercer ou défendre des droits en justice.",
    "Nous pouvons partager des informations personnelles et non personnelles avec des Services tiers de confiance qui nous aident à exploiter le site web et à fournir des services, notamment des hébergeurs, prestataires d’envoi d’e-mails, fournisseurs d’analyse, fournisseurs de bases de données ou de stockage, outils de service client, prestataires de paiement lorsque applicable, prestataires de sécurité, conseillers professionnels et partenaires commerciaux lorsque cela est nécessaire pour le Service. Nous pouvons également divulguer des informations lorsque la loi, une procédure judiciaire, une décision de justice ou une demande réglementaire l’exige, ou lorsque nous estimons raisonnablement que la divulgation est nécessaire pour protéger nos droits ou intérêts, protéger le public ou toute personne, prévenir ou arrêter une activité illégale, contraire à l’éthique ou juridiquement contestable, enquêter sur un abus, ou respecter les lois et règlements applicables.",
    "Ce site web utilise des cookies et technologies similaires pour identifier les zones du site que vous avez visitées, mémoriser des préférences, soutenir des fonctionnalités, améliorer les performances et fournir des statistiques. Les préférences essentielles peuvent inclure le choix relatif aux cookies et la préférence de langue. Les cookies d’analyse optionnels, y compris Google Analytics 4 lorsqu’il est configuré, sont utilisés uniquement après consentement afin de comprendre comment les visiteurs utilisent le site web. Vous pouvez accepter ou refuser les analyses non essentielles. Vous pouvez réinitialiser votre choix via le lien Paramètres des cookies dans le pied de page, et vous pouvez également bloquer ou supprimer les cookies dans les paramètres de votre navigateur. Le blocage ou la suppression des cookies peut affecter les préférences enregistrées ou certaines fonctionnalités du site. Nous ne plaçons pas intentionnellement d’informations personnellement identifiables dans les cookies.",
    "Nous pouvons partager des données limitées de journaux, y compris des adresses IP, avec des fournisseurs d’analyse ou d’infrastructure à des fins de mesure, sécurité, débogage, audit, recherche et reporting. Les informations d’analyse peuvent être utilisées pour estimer une localisation générale, le type d’appareil, le type de navigateur, les informations de connexion, les pages consultées et les schémas d’interaction. Les données d’analyse sont utilisées pour améliorer le site web et les services, et non pour vendre des données personnelles.",
    "Les réponses anonymes au diagnostic ne sont pas conservées. Les informations personnelles transmises dans le cadre d’une demande de rapport, de consultation, de devis ou de toute autre demande qui ne donne pas lieu à une collaboration sont conservées pendant une durée maximale de 12 mois à compter du dernier contact substantiel. Les informations personnelles relatives à une relation client active sont conservées pendant la durée de la collaboration et supprimées au plus tard deux ans après la fin de celle-ci, sauf si une durée plus longue est nécessaire pour respecter une obligation légale, comptable, fiscale, réglementaire ou contractuelle, ou pour établir, exercer ou défendre des droits en justice. Les factures, contrats et autres documents soumis à une durée de conservation obligatoire sont conservés pendant la période prévue par la loi applicable. Les données d’analyse sont conservées conformément aux paramètres de conservation configurés auprès du fournisseur d’analyse concerné. Lorsque les informations ne sont plus nécessaires, nous les supprimons ou les anonymisons lorsque cela est raisonnablement possible. Des copies de sauvegarde peuvent subsister pendant une période limitée lorsque cela est techniquement nécessaire pour prévenir une perte accidentelle.",
    "Nous utilisons des mesures physiques, techniques et organisationnelles raisonnables pour protéger les informations personnelles contre l’accès non autorisé, la perte, l’utilisation abusive, la divulgation, l’altération ou la destruction. Ces mesures peuvent inclure un hébergement sécurisé, des contrôles d’accès, une transmission chiffrée lorsque disponible et des procédures internes. Toutefois, aucun site web, transmission par e-mail, hébergeur, prestataire de paiement, système de chiffrement ou système de sécurité ne peut être garanti comme totalement sécurisé, et nous ne pouvons garantir la sécurité absolue des informations transmises vers ou via le Service.",
    "Les informations collectées via le site web, les communications directes ou les Services tiers peuvent être traitées en Belgique, dans l’Espace économique européen ou dans d’autres pays où notre personnel ou nos prestataires opèrent. Lorsque des données personnelles sont transférées en dehors de l’Espace économique européen, le prestataire concerné est censé s’appuyer sur des garanties appropriées telles que des décisions d’adéquation, des clauses contractuelles types ou d’autres mécanismes de transfert licites.",
    "Selon votre relation avec BrandLabel Agency et les lois applicables, vous pouvez disposer du droit d’accéder à vos données personnelles, de les corriger, les mettre à jour, en limiter le traitement, les supprimer, vous opposer au traitement ou demander leur portabilité. Vous pouvez également retirer votre consentement lorsque le traitement repose sur celui-ci et modifier vos préférences de communication lorsque applicable. Afin de protéger la vie privée et la sécurité, nous pouvons prendre des mesures raisonnables pour vérifier votre identité avant de répondre à une demande. Les mises à jour, corrections, modifications ou suppressions peuvent ne pas affecter les informations déjà traitées légalement, les informations conservées pour des raisons légales ou de sécurité, les informations contenues dans des sauvegardes difficiles ou impossibles à localiser immédiatement, ou les informations déjà transmises à des tiers conformément à cette Politique de confidentialité avant le traitement de la demande.",
    "Si vous êtes l’utilisateur final de l’un de nos clients et souhaitez mettre à jour, supprimer ou recevoir des informations détenues à votre sujet dans un système contrôlé par ce client, vous devrez peut-être contacter l’organisation dont vous êtes client. Lorsque BrandLabel Agency agit uniquement en tant que sous-traitant ou prestataire pour un client, nous pouvons transmettre votre demande à ce client.",
    "Nous nous réservons le droit de transférer des informations à un tiers en cas de vente, fusion, acquisition, restructuration, faillite, transfert d’actifs, cessation d’activité ou opération commerciale similaire impliquant BrandLabel Agency ou toute société affiliée, à condition que le destinataire accepte de traiter les informations conformément à cette Politique de confidentialité ou à un standard de confidentialité équivalent. Nous pouvons également divulguer des informations, y compris des informations personnelles, à des sociétés affiliées lorsque applicable. Une société affiliée désigne une entité qui contrôle directement ou indirectement BrandLabel Agency, est contrôlée par BrandLabel Agency ou est sous contrôle commun avec BrandLabel Agency.",
    "Notre Service peut contenir des liens vers des sites web ou services tiers qui ne sont pas exploités ou contrôlés par BrandLabel Agency. Nous ne sommes pas responsables du contenu, de l’exactitude, des pratiques de confidentialité, des politiques ou de la sécurité des sites web ou services tiers. Lorsque vous quittez notre site web, votre navigation et vos interactions sont régies par les propres conditions et politiques de confidentialité du tiers. Les tiers peuvent utiliser leurs propres cookies ou technologies similaires.",
    "BrandLabel Agency ne collecte pas sciemment d’informations permettant d’identifier personnellement des enfants de moins de 13 ans. Si vous êtes parent ou tuteur et pensez qu’un enfant nous a fourni des Données personnelles, veuillez nous contacter. Si nous apprenons que nous avons collecté des Données personnelles d’un enfant de moins de 13 ans sans consentement approprié, nous prendrons des mesures pour supprimer ces informations.",
    "Le Règlement général sur la protection des données (RGPD) accorde aux personnes situées dans l’Espace économique européen des droits sur leurs Données personnelles et exige que les données personnelles soient traitées de manière loyale, licite, transparente, pour des finalités spécifiques et pas plus longtemps que nécessaire. BrandLabel Agency considère les principes du RGPD comme un standard de base. Les données personnelles doivent être collectées pour des finalités claires, utilisées d’une manière raisonnablement prévisible, protégées de manière appropriée et rendues disponibles pour l’accès, la correction, la suppression, la limitation, l’opposition ou la portabilité lorsque la loi applicable l’exige.",
    "Cette Politique de confidentialité est régie par les lois de Belgique, sans égard aux règles de conflit de lois, sous réserve de tout droit impératif dont vous pourriez bénéficier en vertu du droit local, national, européen ou international applicable. Votre utilisation du site web peut également être soumise à d’autres lois locales, nationales ou internationales applicables.",
    "En utilisant le site web, en nous contactant directement ou en continuant à utiliser le Service après une mise à jour de cette Politique de confidentialité, vous reconnaissez avoir lu cette Politique de confidentialité. Si vous n’acceptez pas cette Politique de confidentialité, vous ne devez pas utiliser le site web ni soumettre d’informations personnelles via le Service. Nous pouvons mettre à jour cette Politique de confidentialité lorsque notre Service, nos prestataires, nos obligations légales ou notre structure commerciale changent, et la dernière version sera publiée sur cette page avec une date mise à jour.",
    "Si vous avez des questions concernant cette Politique de confidentialité ou souhaitez faire une demande relative à la vie privée, contactez-nous à contact@brandlabelagency.com ou utilisez le formulaire de contact en indiquant « privacy request » dans votre message.",
  ],
  nl: [
    "BrandLabel Agency (“wij”, “ons” of “onze”) zet zich in om je privacy te beschermen. Dit Privacybeleid legt uit hoe persoonsgegevens worden verzameld, gebruikt, opgeslagen, beschermd, overgedragen en gedeeld wanneer je brandlabelagency.com bezoekt, rechtstreeks contact met ons opneemt, een rapport, consultatie of offerte aanvraagt, of een gerelateerde dienst van BrandLabel Agency gebruikt. BrandLabel Agency, btw BE1040366570, is de verwerkingsverantwoordelijke. Vragen over privacy kunnen worden gestuurd naar contact@brandlabelagency.com.",
    "Voor dit Privacybeleid verwijzen “Bedrijf”, “wij”, “ons” en “onze” naar BrandLabel Agency; “Website” verwijst naar brandlabelagency.com; “Service” verwijst naar de website en elke dienst die BrandLabel Agency aanbiedt; “Jij” verwijst naar de persoon, onderneming of organisatie die de website gebruikt of contact met ons opneemt; “Persoonsgegevens” betekent informatie die een natuurlijke persoon identificeert of redelijkerwijs kan identificeren; “Apparaat” betekent elke telefoon, tablet, computer of vergelijkbaar apparaat met internetverbinding; “Cookie” betekent een klein gegevensbestand dat door je browser wordt opgeslagen om voorkeuren te onthouden, functionaliteit te ondersteunen of analytics mogelijk te maken; en “Derde dienst” betekent een provider of partner die wordt gebruikt om onze diensten te hosten, exploiteren, analyseren, beveiligen, communiceren, betalingen te verwerken waar van toepassing of te leveren.",
    "Wij kunnen informatie verzamelen die je rechtstreeks verstrekt, waaronder je naam, gebruikersnaam waar van toepassing, bedrijfsnaam, e-mailadres, telefoonnummer wanneer verstrekt, berichtinhoud, details van je serviceaanvraag, audit- of offerte-informatie, bestel- of transactiegegevens waar van toepassing, nieuwsbrief- of communicatievoorkeuren waar van toepassing, en andere informatie die je kiest te verzenden via een formulier, e-mail, enquête, promotie, bestelproces, accountproces of directe communicatie. We kunnen ook technische en gebruiksinformatie verzamelen wanneer je de website bezoekt, waaronder IP-adres, browsertype, apparaattype, besturingssysteem, bezochte pagina’s, data en tijden van toegang, verwijzende pagina’s, geschatte locatie, verbindingsinformatie, taalvoorkeur, cookievoorkeur en server- of beveiligingslogs.",
    "Wij verzamelen informatie wanneer je de website bezoekt, een formulier invult, rechtstreeks contact met ons opneemt, informatie aanvraagt, een offerte aanvraagt, je abonneert op communicatie waar beschikbaar, reageert op een enquête of promotie waar beschikbaar, een bestelling plaatst waar beschikbaar, een account registreert waar beschikbaar, of anderszins met BrandLabel Agency communiceert. We kunnen ook informatie ontvangen van Derde diensten die worden gebruikt voor hosting, analytics, e-mailbezorging, beveiliging, fraudepreventie, klantcommunicatie, databaseopslag, betalingsverwerking waar van toepassing, klantenservice en openbare bronnen zoals bedrijfswebsites of socialmediapagina’s.",
    "Wij gebruiken de verzamelde informatie om op vragen te reageren, audits of offertes te leveren, met je te communiceren, de website te verbeteren, je ervaring te personaliseren, klantenservice te verbeteren, transacties te verwerken waar van toepassing, formulieren, enquêtes of promoties te beheren waar van toepassing, servicegerelateerde e-mails te sturen, gevraagde of toegestane communicatie te sturen, de veiligheid te behouden, misbruik te voorkomen, technische problemen op te lossen, websiteprestaties te analyseren en onze diensten te verbeteren. Wij sturen geen ongevraagde commerciële e-mails. Wanneer marketingmails worden gebruikt, kun je je uitschrijven of bezwaar maken via de instructies in die communicatie.",
    "De wettelijke grondslag voor verwerking hangt af van de context. Wij verwerken contact- en aanvraaggegevens om op je verzoek te reageren en stappen te nemen vóór een mogelijke dienstverleningsovereenkomst. Wij verwerken operationele en beveiligingsinformatie op basis van ons gerechtvaardigd belang om een veilige en betrouwbare website te exploiteren. Wij verwerken analytics alleen wanneer je toestemming geeft voor analytische cookies. Sommige informatie kunnen wij verwerken wanneer dat nodig is om te voldoen aan wettelijke, boekhoudkundige, fiscale, regelgevende of beveiligingsverplichtingen, of om juridische claims vast te stellen, uit te oefenen of te verdedigen.",
    "Wij kunnen persoonlijke en niet-persoonlijke informatie delen met vertrouwde Derde diensten die ons helpen de website te exploiteren en diensten te leveren, waaronder hostingproviders, e-mailproviders, analyticsproviders, database- of opslagproviders, klantenservicetools, betalingsverwerkers waar van toepassing, beveiligingsproviders, professionele adviseurs en zakelijke partners wanneer nodig voor de Service. Wij kunnen ook informatie openbaar maken wanneer dit vereist is door de wet, een juridische procedure, gerechtelijk bevel, verzoek van een toezichthouder, of wanneer wij redelijkerwijs menen dat openbaarmaking nodig is om onze rechten of belangen te beschermen, het publiek of een persoon te beschermen, onwettige, onethische of juridisch aanvechtbare activiteiten te voorkomen of stoppen, misbruik te onderzoeken of te voldoen aan toepasselijke wet- en regelgeving.",
    "Deze website gebruikt cookies en vergelijkbare technologieën om te identificeren welke delen van de website je hebt bezocht, voorkeuren te onthouden, functionaliteit te ondersteunen, prestaties te verbeteren en analytics te leveren. Essentiële voorkeuren kunnen de cookiekeuze en taalvoorkeur omvatten. Optionele analytische cookies, waaronder Google Analytics 4 wanneer geconfigureerd, worden alleen gebruikt na toestemming om te begrijpen hoe bezoekers de website gebruiken. Je kunt niet-essentiële analytics accepteren of weigeren. Je kunt je keuze wissen via de link Cookie-instellingen in de footer, en je kunt cookies ook blokkeren of verwijderen via je browserinstellingen. Het blokkeren of verwijderen van cookies kan opgeslagen voorkeuren of bepaalde websitefunctionaliteit beïnvloeden. Wij plaatsen niet bewust persoonlijk identificeerbare informatie in cookies.",
    "Wij kunnen beperkte logbestanden, waaronder IP-adressen, delen met analytics- of infrastructuurproviders voor meting, beveiliging, debugging, audit, onderzoek en rapportage. Analyticsinformatie kan worden gebruikt om algemene locatie, apparaattype, browsertype, verbindingsinformatie, bekeken pagina’s en interactiepatronen te schatten. Analyticsgegevens worden gebruikt om de website en diensten te verbeteren, niet om persoonsgegevens te verkopen.",
    "Anonieme antwoorden op de diagnose worden niet opgeslagen. Persoonsgegevens die worden verstrekt in verband met een rapport, consultatie, offerte of andere aanvraag die niet tot een samenwerking leidt, worden maximaal 12 maanden na het laatste inhoudelijke contact bewaard. Persoonsgegevens met betrekking tot een actieve klantrelatie worden gedurende de samenwerking bewaard en uiterlijk twee jaar na het einde van de samenwerking verwijderd, tenzij een langere termijn noodzakelijk is om te voldoen aan een wettelijke, boekhoudkundige, fiscale, regelgevende of contractuele verplichting, of om rechtsvorderingen vast te stellen, uit te oefenen of te verdedigen. Facturen, contracten en andere documenten waarvoor een verplichte bewaartermijn geldt, worden bewaard gedurende de termijn die de toepasselijke wet voorschrijft. Analysegegevens worden bewaard overeenkomstig de bewaartermijnen die bij de betreffende analyseprovider zijn ingesteld. Wanneer gegevens niet langer nodig zijn, verwijderen of anonimiseren wij deze waar dat redelijkerwijs mogelijk is. Back-upkopieën kunnen gedurende een beperkte periode blijven bestaan wanneer dit technisch noodzakelijk is om onbedoeld verlies te voorkomen.",
    "Wij gebruiken redelijke fysieke, technische en organisatorische maatregelen om persoonsgegevens te beschermen tegen ongeoorloofde toegang, verlies, misbruik, openbaarmaking, wijziging of vernietiging. Deze maatregelen kunnen veilige hosting, toegangscontroles, versleutelde overdracht waar beschikbaar en interne procedures omvatten. Geen enkele website, e-mailoverdracht, hostingprovider, betalingsprovider, encryptiesysteem of beveiligingssysteem kan echter volledig veilig worden gegarandeerd, en wij kunnen geen absolute veiligheid garanderen van informatie die naar of via de Service wordt verzonden.",
    "Informatie die via de website, directe communicatie of Derde diensten wordt verzameld, kan worden verwerkt in België, de Europese Economische Ruimte of andere landen waar ons personeel of onze dienstverleners actief zijn. Wanneer persoonsgegevens buiten de Europese Economische Ruimte worden overgedragen, wordt van de betreffende provider verwacht dat deze passende waarborgen gebruikt, zoals adequaatheidsbesluiten, standaardcontractbepalingen of andere rechtmatige overdrachtsmechanismen.",
    "Afhankelijk van je relatie met BrandLabel Agency en de toepasselijke wetgeving kun je het recht hebben om toegang te vragen tot je persoonsgegevens, deze te corrigeren, bij te werken, de verwerking te beperken, te verwijderen, bezwaar te maken tegen verwerking of gegevensoverdraagbaarheid te vragen. Je kunt ook toestemming intrekken wanneer verwerking op toestemming is gebaseerd en communicatievoorkeuren wijzigen waar van toepassing. Ter bescherming van privacy en veiligheid kunnen wij redelijke stappen nemen om je identiteit te verifiëren voordat wij op een verzoek reageren. Updates, correcties, wijzigingen of verwijderingen hebben mogelijk geen effect op informatie die al rechtmatig is verwerkt, informatie die wordt bewaard om juridische of veiligheidsredenen, informatie in back-ups die moeilijk of onmogelijk onmiddellijk te lokaliseren zijn, of informatie die al aan derden is verstrekt in overeenstemming met dit Privacybeleid voordat het verzoek werd verwerkt.",
    "Als je eindgebruiker bent van een van onze klanten en informatie over jou in een door die klant beheerd systeem wilt bijwerken, verwijderen of ontvangen, moet je mogelijk contact opnemen met de organisatie waarvan je klant bent. Wanneer BrandLabel Agency alleen optreedt als verwerker of dienstverlener voor een klant, kunnen wij je verzoek doorverwijzen naar die klant.",
    "Wij behouden ons het recht voor informatie over te dragen aan een derde partij in geval van verkoop, fusie, overname, herstructurering, faillissement, overdracht van activa, stopzetting van activiteiten of een vergelijkbare zakelijke transactie waarbij BrandLabel Agency of een gelieerde onderneming betrokken is, op voorwaarde dat de ontvangende partij ermee instemt de informatie te behandelen in overeenstemming met dit Privacybeleid of een gelijkwaardige privacystandaard. Wij kunnen ook informatie, waaronder persoonsgegevens, delen met gelieerde ondernemingen waar van toepassing. Een gelieerde onderneming betekent een entiteit die BrandLabel Agency direct of indirect controleert, door BrandLabel Agency wordt gecontroleerd of onder gemeenschappelijke controle staat met BrandLabel Agency.",
    "Onze Service kan links bevatten naar websites of diensten van derden die niet door BrandLabel Agency worden beheerd of gecontroleerd. Wij zijn niet verantwoordelijk voor de inhoud, juistheid, privacypraktijken, beleidsregels of beveiliging van websites of diensten van derden. Wanneer je onze website verlaat, worden je navigatie en interactie beheerst door de voorwaarden en privacyverklaring van die derde partij. Derden kunnen hun eigen cookies of vergelijkbare technologieën gebruiken.",
    "BrandLabel Agency verzamelt niet bewust persoonlijk identificeerbare informatie van kinderen jonger dan 13 jaar. Als je ouder of voogd bent en denkt dat een kind Persoonsgegevens aan ons heeft verstrekt, neem dan contact met ons op. Als wij ontdekken dat wij Persoonsgegevens van een kind jonger dan 13 jaar zonder passende toestemming hebben verzameld, nemen wij stappen om die informatie te verwijderen.",
    "De Algemene Verordening Gegevensbescherming (AVG/GDPR) geeft personen in de Europese Economische Ruimte rechten over hun Persoonsgegevens en vereist dat persoonsgegevens eerlijk, rechtmatig, transparant, voor specifieke doeleinden en niet langer dan noodzakelijk worden verwerkt. BrandLabel Agency hanteert de GDPR-principes als basisnorm. Persoonsgegevens moeten voor duidelijke doeleinden worden verzameld, worden gebruikt op een manier die mensen redelijkerwijs kunnen verwachten, passend worden beschermd en beschikbaar zijn voor toegang, correctie, verwijdering, beperking, bezwaar of overdraagbaarheid waar de toepasselijke wet dit vereist.",
    "Dit Privacybeleid wordt beheerst door de wetten van België, zonder rekening te houden met conflictenrecht, behoudens eventuele dwingende rechten die je hebt onder toepasselijk lokaal, nationaal, Europees of internationaal recht. Je gebruik van de website kan ook onderworpen zijn aan andere toepasselijke lokale, nationale of internationale wetten.",
    "Door de website te gebruiken, rechtstreeks contact met ons op te nemen of de Service te blijven gebruiken nadat dit Privacybeleid is bijgewerkt, erken je dat je dit Privacybeleid hebt gelezen. Als je niet akkoord gaat met dit Privacybeleid, mag je de website niet gebruiken of persoonsgegevens via de Service indienen. Wij kunnen dit Privacybeleid bijwerken wanneer onze Service, providers, wettelijke verplichtingen of bedrijfsstructuur wijzigen, en de nieuwste versie wordt op deze pagina gepubliceerd met een bijgewerkte datum.",
    "Als je vragen hebt over dit Privacybeleid of een privacyverzoek wilt doen, neem dan contact op via contact@brandlabelagency.com of gebruik het contactformulier en vermeld “privacy request” in je bericht.",
  ],
};

export function PrivacyContent() {
  const { language } = useLanguage();
  const paragraphs = policyText[language];

  return (
    <section className="bg-[#fbfaf7] py-16 sm:py-24">
      <Container>
        <article className="premium-card rounded-md p-6 sm:p-8 lg:p-10">
          <div className="space-y-5 text-base leading-7 text-slate-700 lg:text-lg lg:leading-8">
            {paragraphs.map((paragraph) => (
              <p key={paragraph}>{paragraph}</p>
            ))}
          </div>
        </article>
      </Container>
    </section>
  );
}
